### ISSUE TITLE
 Syncthing同步

### ISSUE THREAD

**Issue by liheyuting** [einverne/einverne.github.io#13]
Hi Einverne,
很感谢你的博客，种草了obsidian和syncthing两个软件，真的非常棒。
我遇到了一些小问题，也在网上搜索了下，想请教syncthing同步是否需要设备同时在线？

**遇到的问题：** 同步失败，显示如下：
![image](https://user-images.githubusercontent.com/25094288/84727502-c234a380-afc1-11ea-9687-cc691eb8447c.png)
**设备背景**：在不同的网络下，也已经设置了global状态，0.0.0.0:8384

我在网络上搜索了下，也在不同的博客里看了别人的教程啥的，感觉都没什么问题，不过也没查到相关问题；在官网说明和help里好像也没找到（maybe poor english）

想要问问看你，是不是因为需要设备同时在线的情况呀？

**ref blog link:**
[分布式同步工具 Syncthing](http://einverne.github.io/post/2019/10/syncthing.html)

**Comment by einverne** [comment]
如果使用 Syncthing 自己的 Discovery 服务器，那么保证你自己的机器能够连接互联网即可，但如果你是在你的局域网中使用，你可能需要搭建你自己的全局发现服务器。

另外如果你要同步其它机器上的文件，那么那一台机器需要开机并且处于联网状态的。

**Comment by liheyuting** [comment]
好的非常感谢！
