### ISSUE TITLE
date 命令 时间戳位数 错误

### ISSUE THREAD

**Issue by yanchaosb123** [einverne/einverne.github.io#7]
在 网页 http://einverne.github.io/post/2017/09/use-shell-command-to-convert-timestamp-and-date.html 中
![image](https://user-images.githubusercontent.com/19329937/67184144-ad454780-f415-11e9-97c9-e081f5a62bf7.png)

date +%s  为10 位的时间戳，却写成了11位， 其他类似多加了一位

**Comment by einverne** [comment]
感谢指正，已经修改。
